### ISSUE TITLE
Trouble installing R packages via rip.py

### ISSUE THREAD

**Issue by rmnppt** [algorithmiaio/langpacks#24]
I am trying to install the following R packages by adding the following lines to `packages.txt`

```
dplyr
tidytext
```

When I subsequently compile and run the algorithm I get either:

```
Error: Failed to start algorithm - Loading required package: methods Error in library("tidytext") : there is no package called ‘tidytext’ Calls: source -> withVisible -> eval -> eval -> library Execution halted Failed to load: exited with code 1
```

or:

```
Error: Failed to start algorithm - Loading required package: methods Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : namespace ‘R6’ 2.2.0 is being loaded, but >= 2.2.2 is required Error: package or namespace load failed for ‘dplyr’ Execution halted Failed to load: exited with code 1
```

depending on which package I load first. I started to go through a combination of installations from the archives of those two packages (sometimes older versions installed and ran fine) but is there something in the workflow of `build` that would be breaking these installations?

**Comment by rmnppt** [comment]
Am I right in thinking that the contents of `bin/` are non write-able for the algorithm developer?

**Comment by jamesatha** [comment]
It looks like `tidytext` is the one causing the problem here. This is due to the fact that we are running an older version of R. We are actively working on upgrading R but that will be a while. In the meantime, this set of dependencies should allow you to use the two packages you need:
```#For tidytext
mnormt
foreign
reshape2
hunspell
tokenizers
janeaustenr
-t https://cran.r-project.org/src/contrib/R6_2.2.2.tar.gz
-t https://cran.r-project.org/src/contrib/Archive/nlme/nlme_3.1-131.tar.gz
-t https://cran.r-project.org/src/contrib/Archive/psych/psych_1.7.8.tar.gz
-t https://cran.r-project.org/src/contrib/Archive/broom/broom_0.4.3.tar.gz
-t https://cran.r-project.org/src/contrib/Archive/tidytext/tidytext_0.1.5.tar.gz
dplyr
```

**Comment by rmnppt** [comment]
Great thank you. That worked fine. I will close this one and open another regarding R versions.
Your help is much appreciated.
