### ISSUE TITLE
R version default

### ISSUE THREAD

**Issue by rmnppt** [algorithmiaio/langpacks#26]
I don't know if this is the most desirable behaviour for an R build or not but could it be that the latest version of R could be the default and then the user could override that with a specific version if they needed it? This might also reduce package installation problems.

**Comment by pmcq** [comment]
Hi @rmnppt thanks for reaching out.  This is an issue we've actually seen across a couple of different languages, and we are currently working to address.  Our overall goal is that users should be able to select the version of R (or other langauge/framework in use) for their algorithm.  I expect we would continue to have the same default version of R for backward compatibility, and other versions would all be explicit for reproducibility (as opposed to a more generic "latest").

We will be rolling out this feature on a language by language basis and will update you when we support R.

**Comment by rmnppt** [comment]
Hi @pmcq thanks for getting back to me, that makes sense. Keep up the good work! and feel free to close this issue if its not of use here.
